version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejscn/node
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - .:/src
    ports:
      - "4000:4000"
